@echo off
echo Installing required libraries...
py -m pip install -r requirements.txt
echo Training ATS model...
py src\train_model.py
echo Starting AI Career Assistant...
py -m streamlit run app\app.py
pause
